local C = {
    NAME = "微信读书",
    VERSION = "0.1.1",
    PLUGIN_DIR = "wereadlite.koplugin",
    SETTINGS_FILE = "wereadlite.lua",
    ENTRY_FILENAME = "微信读书.epub",
    ENTRY_COVER = "resources/front.png",
    ENTRY_SUFFIX = "epub",
    LOG_TAG = "wereadlite",
    KINDLE_UA = "Mozilla/5.0 (X11; U; Linux armv71 like Android; en-us) AppleWebKit/531.2+ (KHTML, like Gecko) Version/5.0 Safari/533.2+ Kindle/3.0+",
    ORIGIN = "https://weread.qq.com",
    LOGIN_URL = "https://weread.qq.com/wrwebsimplenjlogic/login",
    LOGIN_GETUID_URL = "https://weread.qq.com/wrwebsimplenjlogic/api/getuid?platform=desktop",
    LOGIN_QRCODE_URL = "https://weread.qq.com/wrwebsimplenjlogic/api/qrcode",
    LOGIN_INFO_URL = "https://weread.qq.com/wrwebsimplenjlogic/api/getlogininfo",
    LOGIN_WEBLOGIN_URL = "https://weread.qq.com/wrwebsimplenjlogic/api/weblogin",
    SHELF_URL = "https://weread.qq.com/wrwebsimplenjlogic/shelf",
    SHELF_MORE_URL = "https://weread.qq.com/wrwebsimplenjlogic/api/shelfloadmore",
    READER_URL = "https://weread.qq.com/wrwebsimplenjlogic/reader",
    CATALOG_MORE_URL = "https://weread.qq.com/wrwebsimplenjlogic/api/catalogloadmore",
    READER_FONT_URL = "https://cdn.weread.qq.com/app/assets/test-font/fzys_reversed.ttf",
    READER_URL = "https://weread.qq.com/wrwebsimplenjlogic/reader",
    CATALOG_MORE_URL = "https://weread.qq.com/wrwebsimplenjlogic/api/catalogloadmore",
    READER_FONT_URL = "https://cdn.weread.qq.com/app/assets/test-font/fzys_reversed.ttf",
    BOOKREAD_URL = "https://weread.qq.com/wrwebsimplenjlogic/api/bookread?platform=desktop",
    ADD_BOOKMARK_URL = "https://weread.qq.com/wrwebsimplenjlogic/api/addbookmark?platform=desktop",
    REMOVE_BOOKMARK_URL = "https://weread.qq.com/wrwebsimplenjlogic/api/removebookmark?platform=desktop",
    SKILL_PAGE = "https://weread.qq.com/r/weread-skills",
    SKILL_APIKEY_URL = "https://weread.qq.com/api/skills/apikeyGet",
    SKILL_GATEWAY_URL = "https://i.weread.qq.com/api/agent/gateway",
    SKILL_VERSION = "1.0.4",
    WEB_UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0",
    API_PAGE_SIZE = 20,
    GRID_ROWS = 4,
    GRID_COLS = 5,
    FIRST_PAGE_BOOKS = 10,
    PAGE_BOOKS = 20,
}

return C
